### ISSUE TITLE
ec2.crt outdated

### ISSUE THREAD

**Issue by morriswinkler-simple** [owncloud/proxy#5]
if you still maintain this code, ec2.crt is outdated.

Or add a comment to the Readme that this is unmaintained.

**Comment by tboerger** [comment]
If you look at https://github.com/owncloudarchive you can see that the entire organization holds outdated/unmaintained apps.

**Comment by DeepDiver1975** [comment]
> Or add a comment to the Readme that this is unmaintained.

we transfered the repo a few days back -> close
